project:
  type: website

website:
  sidebar:
    style: docked
    title: "{{< var department-abbrev >}} {{< var number >}}"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    contents:
      - href: index.qmd
        text: Home 
      - href: staff.qmd
        text: Staff
      - href: syllabus.qmd
        text: Syllabus
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



